# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  rubocop:
    docker:
      # https://hub.docker.com/r/circleci/ruby/tags/ から使うイメージを選ぶ
      # Gemfileと同じバージョンでないとFailedする
      - image: circleci/ruby:2.6.3-node-browsers-legacy
        environment:
          # 環境指定
          RAILS_ENV: test
          # Service container image available at `host: localhost`
          POSTGRES_HOST: 127.0.0.1
      # https://hub.docker.com/r/circleci/postgres から使うイメージを選ぶ
      - image: circleci/postgres:11.5
        environment:
          # config/database.ymlの値を入力
          POSTGRES_USER: postgres
          POSTGRES_DB: household_account_on_rails_test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # Rubocop
      - run:
          name: Rubocop
          command: bundle exec rubocop

  rspec:
    docker:
      # https://hub.docker.com/r/circleci/ruby/tags/ から使うイメージを選ぶ
      - image: circleci/ruby:2.6.3-node-browsers-legacy
        environment:
          # 環境指定
          RAILS_ENV: test
          # Service container image available at `host: localhost`
          POSTGRES_HOST: 127.0.0.1
      # https://hub.docker.com/r/circleci/postgres から使うイメージを選ぶ
      - image: circleci/postgres:11.5
        environment:
          # config/database.ymlの値を入力
          POSTGRES_USER: postgres
          POSTGRES_DB: household_account_on_rails_test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # dbの起動を待つための処理を入れる
      - run:
        name: install dockerize
        command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
        environment:
        DOCKERIZE_VERSION: v0.3.0
      - run:
        name: Wait for db
        command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load
      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2
  rubocop_rspec:
    jobs:
      - rubocop
      - rspec:
          requires:
            - rubocop
