default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: household_account_on_rails_development


test:
  <<: *default
  database: household_account_on_rails_test
